python trainer_chois.py \
--window=120 \
--batch_size=32 \
--data_root_folder="/ailab/user/lishujia-hdd/chois_release/data/processed_data" \
--pretrained_model="/ssd1/lishujia/chois_release/chois_release_mesh_condition_inter5frames/chois_window_120_set0116/weights/model-16.pt" \
--save_res_folder="./chois_long_seq_mesh_results" \
--input_first_human_pose \
--use_random_frame_bps \
--add_language_condition \
--use_object_keypoints \
--add_semantic_contact_labels \
--loss_w_feet=1 \
--loss_w_fk=0.5 \
--loss_w_obj_pts=1 \
--test_sample_res \
--use_long_planned_path \
--test_object_name="all" \
--test_scene_name="frl_apartment_4" \
--use_guidance_in_denoising