python trainer_chois.py \
--window=120 \
--batch_size=32 \
--data_root_folder="/ailab/user/lishujia-hdd/chois_release/data/processed_data" \
--project="/ssd1/lishujia/chois_release/chois_release_object_split/" \
--exp_name="chois_window_120_set0116_mesh_12" \
--wandb_pj_name="chois_interaction_diffusion" \
--entity="lishujia678" \
--input_first_human_pose \
--use_random_frame_bps \
--add_language_condition \
--use_object_keypoints \
--loss_w_feet=1 \
--loss_w_fk=0.5 \
--loss_w_obj_pts=1 \
--use_object_split \
--add_mesh_conditions\
